@baseUrl = http://localhost:5000/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImR1bmcudHJhbnZhbiIsImlkIjoiZTYxMmQ3YzItNjU5ZS00Njk3LWE4ODEtNDgyNWM3ZTNmNTM0Iiwicm9sZSI6MSwiaWF0IjoxNjU4MTEzMTMyLCJleHAiOjE2NTgxMTY3MzJ9.uNbXAteyNyP1kQklE_pG9NoTVO6OOcKuNCOxX2fngwg

# @name getClasses
GET {{baseUrl}}/class
Authorization: Bearer {{token}}

###

# @name getClass
GET {{baseUrl}}/class/103175
Authorization: Bearer {{token}}

###

# @name createClass
POST {{baseUrl}}/class
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "classCode": "103177",
  "subjectCode": "ET2031",
  "subjectName": "Kỹ thuật lập trình",
  "semester": "20222",
  "room": "D3-201"
}

###

# @name updateClass
PUT {{baseUrl}}/class/96d01413-97f0-4972-aae7-125bb64e22d9
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "classCode": "123123",
  "subjectName": "Nhập môn CNTT",
  "semester": "20221",
  "room": "D9-401"
}

###

# @name addStudent
POST {{baseUrl}}/class/addStudent
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "classCode": "103176",
  "studentCode": "20210011"
}

# @name deleteStudent
DELETE {{baseUrl}}/class/deleteStudent
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "classCode": "103176",
  "studentCode": "20210011"
}
