@baseUrl = http://localhost:5000/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxpbmgubnQyMDAwMDEiLCJpZCI6ImI2OTE1OWU3LTNmYjUtNGRiYi1iZjVlLTZmZTEzNGQ4ZmEyYyIsInJvbGUiOjAsImlhdCI6MTY1ODA1MzgzMCwiZXhwIjoxNjU4MDU3NDMwfQ.NQ4KfmEEbpcDWxBRCbrv45wlH1NQ1FZCOK7Aoo8MOB4

# @name getMe
GET {{baseUrl}}/students/me
Authorization: Bearer {{token}}


###

# @name createStudent
POST {{baseUrl}}/students
Content-Type: application/json

{
  "fullname": "Nguyễn Thị Linh",
  "code": "20200001"
}
