@baseUrl = http://localhost:5000/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imh1eS5ueDE5MjI0NCIsImlkIjoiYmZmNGQ3MGQtYmNiNi00MTQyLTliMjctY2FjZjAwN2JkYWI1Iiwicm9sZSI6MCwiaWF0IjoxNjU4MTIxMjA5LCJleHAiOjE2NTgxMjQ4MDl9.elfG0IHntnDaGcUiJfmwhn5rhnktkLoO1dNMbUofHaw

# @name getMe
GET {{baseUrl}}/students/me
Authorization: Bearer {{token}}

###

# @name createStudent
POST {{baseUrl}}/students
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "fullname": "Nguyễn Xuân Huy",
  "code": "20192244"
}

###

# @name requestJoinClass
POST {{baseUrl}}/class/request-join-class
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "classCode": "103176"
}

