@baseUrl = http://localhost:5000/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRhbjAxIiwiaWQiOiI5ODk1NDM0YS0wMDVlLTQ0N2UtYjU1ZS1jMDUwMzA4NjkxZjgiLCJyb2xlIjoyLCJpYXQiOjE2NTgxMTM5NzQsImV4cCI6MTY1ODExNzU3NH0.fs5-0KoOwAwYzfGLY_yrDSB4pUVQMXPRmqGjuDa1lEo

# @name getMe
GET {{baseUrl}}/students/me
Authorization: Bearer {{token}}


###

# @name createStudent
POST {{baseUrl}}/students
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "fullname": "Nguyễn Xuân Huy",
  "code": "20192244"
}
