@baseUrl = http://localhost:5000/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImR1bmcudHJhbnZhbiIsImlkIjoiYzBiZDFmYjItOGFiMS00OTVjLTk2NDgtYzEzY2JlZGY3YTJhIiwicm9sZSI6MSwiaWF0IjoxNjU4MDU2MTQzLCJleHAiOjE2NTgwNTk3NDN9.3FvlCi6pH8_0MgBKsGX5wGv0RLpHCkiLOWp17b1nAJ8

# @name getMe
GET {{baseUrl}}/teachers/me
Authorization: Bearer {{token}}

###

# @name createTeacher
POST {{baseUrl}}/teachers
Content-Type: application/json

{
  "fullname": "Trần Văn Dũng",
  "code": "et001"
}
