@baseUrl = http://localhost:5000/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRhbjAxIiwiaWQiOiI5ODk1NDM0YS0wMDVlLTQ0N2UtYjU1ZS1jMDUwMzA4NjkxZjgiLCJyb2xlIjoyLCJpYXQiOjE2NTg1OTA0NDYsImV4cCI6MTY1ODU5NDA0Nn0.FjWT1T5hG6wmE865Il27nPs_22uTwp-TQn5nHyWiMkA

# @name getMe
GET {{baseUrl}}/teachers/me
Authorization: Bearer {{token}}

###

# @name createTeacher
POST {{baseUrl}}/teachers
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "fullname": "Trần Văn Dũng",
  "code": "et001"
}
