@baseUrl = http://localhost:5000/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImR1bmcudHJhbnZhbiIsImlkIjoiYzBiZDFmYjItOGFiMS00OTVjLTk2NDgtYzEzY2JlZGY3YTJhIiwicm9sZSI6MSwiaWF0IjoxNjU4MDg1NjY0LCJleHAiOjE2NTgwODkyNjR9.RDVkPA4PNlbwtE-w_bPKAPonFpE4-SoJ414jraLaFjk

# @name getMe
GET {{baseUrl}}/teachers/me
Authorization: Bearer {{token}}

###

# @name createTeacher
POST {{baseUrl}}/teachers
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "fullname": "Trần Văn Dũng",
  "code": "et001"
}
