@baseUrl = http://localhost:5000/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImR1bmcudHJhbnZhbiIsImlkIjoiYzBiZDFmYjItOGFiMS00OTVjLTk2NDgtYzEzY2JlZGY3YTJhIiwicm9sZSI6MSwiaWF0IjoxNjU4MDU2MTQzLCJleHAiOjE2NTgwNTk3NDN9.3FvlCi6pH8_0MgBKsGX5wGv0RLpHCkiLOWp17b1nAJ8

# @name signup
POST {{baseUrl}}/users/signup
Content-Type: application/json

{
  "username": "tan01",
  "password": "123456",
  "comfirmPassword": "123456",
  "role": 2
}

###

# @name signin
POST {{baseUrl}}/users/signin
Content-Type: application/json

{
  "username": "huy.nx192244",
  "password": "123456",
  "role": 0
}

###

# @name changePassword
PUT {{baseUrl}}/users/change-password
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "oldPassword": "123",
  "password": "123456",
  "confirmPassword": "123456"
}
